// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Runtime.Serialization;

namespace System.Management.Automation
{
    
    /// <remarks>
    /// Instances of this exception class are usually generated by the
    /// PowerShell Engine.  It is unusual for code outside the PowerShell Engine
    /// to create an instance of this class.
    /// </remarks>
    public class PSInvalidOperationException
            : InvalidOperationException, IContainsErrorRecord
    {
        #region ctor
        
        /// <returns>Constructed object.</returns>
        public PSInvalidOperationException()
            : base()
        {
        }

        #region Serialization
        
        /// <param name="info">Serialization information.</param>
        /// <param name="context">Streaming context.</param>
        /// <returns>Constructed object.</returns>
        [Obsolete("Legacy serialization support is deprecated since .NET 8", DiagnosticId = "SYSLIB0051")] 
        protected PSInvalidOperationException(SerializationInfo info,
                           StreamingContext context)
        {
            throw new NotSupportedException();
        }
        #endregion Serialization

        
        /// <param name="message"></param>
        /// <returns>Constructed object.</returns>
        public PSInvalidOperationException(string message)
            : base(message)
        {
        }

        
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        /// <returns>Constructed object.</returns>
        public PSInvalidOperationException(string message,
                                            Exception innerException)
                : base(message, innerException)
        {
        }

        
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        /// <param name="errorId"></param>
        /// <param name="errorCategory"></param>
        /// <param name="target"></param>
        /// <returns>Constructed object.</returns>
        internal PSInvalidOperationException(string message, Exception innerException, string errorId, ErrorCategory errorCategory, object target)
            : base(message, innerException)
        {
            _errorId = errorId;
            _errorCategory = errorCategory;
            _target = target;
        }
        #endregion ctor

        
        /// <value></value>
        /// <remarks>
        /// Note that ErrorRecord.Exception is
        /// <see cref="System.Management.Automation.ParentContainsErrorRecordException"/>.
        /// </remarks>
        public ErrorRecord ErrorRecord
        {
            get
            {
                _errorRecord ??= new ErrorRecord(
                    new ParentContainsErrorRecordException(this),
                    _errorId,
                    _errorCategory,
                    _target);

                return _errorRecord;
            }
        }

        private ErrorRecord _errorRecord;
        private string _errorId = "InvalidOperation";

        internal void SetErrorId(string errorId)
        {
            _errorId = errorId;
        }

        private readonly ErrorCategory _errorCategory = ErrorCategory.InvalidOperation;
        private readonly object _target = null;
    }
}
