// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Runtime.Serialization;

namespace System.Management.Automation
{
    
    /// <remarks>
    /// Instances of this exception class are usually generated by the
    /// PowerShell Engine.  It is unusual for code outside the PowerShell Engine
    /// to create an instance of this class.
    /// </remarks>
    public class PSNotImplementedException
            : NotImplementedException, IContainsErrorRecord
    {
        #region ctor
        
        /// <returns>Constructed object.</returns>
        public PSNotImplementedException()
            : base()
        {
        }

        #region Serialization
        
        /// <param name="info">Serialization information.</param>
        /// <param name="context">Streaming context.</param>
        /// <returns>Constructed object.</returns>
        [Obsolete("Legacy serialization support is deprecated since .NET 8", DiagnosticId = "SYSLIB0051")] 
        protected PSNotImplementedException(SerializationInfo info,
                                              StreamingContext context)
        {
            throw new NotSupportedException();
        }        
        #endregion Serialization

        
        /// <param name="message"></param>
        /// <returns>Constructed object.</returns>
        public PSNotImplementedException(string message)
            : base(message)
        {
        }

        
        /// <param name="message"></param>
        /// <param name="innerException"></param>
        /// <returns>Constructed object.</returns>
        public PSNotImplementedException(string message,
                        Exception innerException)
                : base(message, innerException)
        {
        }
        #endregion ctor

        
        /// <value></value>
        /// <remarks>
        /// Note that ErrorRecord.Exception is
        /// <see cref="System.Management.Automation.ParentContainsErrorRecordException"/>.
        /// </remarks>
        public ErrorRecord ErrorRecord
        {
            get
            {
                _errorRecord ??= new ErrorRecord(
                    new ParentContainsErrorRecordException(this),
                    _errorId,
                    ErrorCategory.NotImplemented,
                    null);

                return _errorRecord;
            }
        }

        private ErrorRecord _errorRecord;
        private readonly string _errorId = "NotImplemented";
    }
}
