<Project>
  <PropertyGroup>
      <TargetFrameworks>net10.0</TargetFrameworks>
      <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
      <!-- summaries -->
      <NoWarn>$(NoWarn);SA1517;SA1002;CS1591;SA1507;SA1001;SA1516</NoWarn>
      <!-- never used -->
      <NoWarn>$(NoWarn);CS0067</NoWarn>
  </PropertyGroup>
</Project>
