<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project=".\Analyzers.props" />

  
  <Target Name="GetPSCoreVersionFromGit"
    BeforeTargets="_GenerateRestoreProjectSpec;GenerateNuspec;BeforeBuild"
  >

    <Exec Command='git describe --abbrev=60 --long'
          WorkingDirectory="$(MSBuildProjectDirectory)"
          ConsoleToMSBuild="true"
          StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="PowerShellVersion" />
    </Exec>

    <PropertyGroup Condition = "'$(ReleaseTag)' != ''">
      

      
      <RegexReleaseTag>^((\d+).(\d+).(\d+))(-(\w+)(.(\d+))?)?$</RegexReleaseTag>
      <ReleaseTagVersionPart>$([System.Text.RegularExpressions.Regex]::Match($(ReleaseTag), $(RegexReleaseTag)).Groups[1].Value)</ReleaseTagVersionPart>
      <ReleaseTagSemVersionPart>$([System.Text.RegularExpressions.Regex]::Match($(ReleaseTag), $(RegexReleaseTag)).Groups[8].Value)</ReleaseTagSemVersionPart>
      <ReleaseTagSemVersionPrereleaseNamePart>$([System.Text.RegularExpressions.Regex]::Match($(ReleaseTag), $(RegexReleaseTag)).Groups[6].Value)</ReleaseTagSemVersionPrereleaseNamePart>
      
      <RCIncrementValue>100</RCIncrementValue>
      
      <GAIncrementValue>500</GAIncrementValue>
      <ReleaseTagSemVersionPart Condition = "'$(ReleaseTagSemVersionPrereleaseNamePart)' == 'rc'">$([MSBuild]::Add($(ReleaseTagSemVersionPart), $(RCIncrementValue)))</ReleaseTagSemVersionPart>
      
      <PSCoreBuildVersion>$(ReleaseTag)</PSCoreBuildVersion>
      
      <PSCoreFileVersion Condition = "'$(ReleaseTagSemVersionPart)' != ''">$(ReleaseTagVersionPart).$(ReleaseTagSemVersionPart)</PSCoreFileVersion>
      
      <PSCoreFileVersion Condition = "'$(PSCoreFileVersion)' == ''">$(ReleaseTagVersionPart).$(GAIncrementValue)</PSCoreFileVersion>
      
      <FileVersion>$(PSCoreFileVersion)</FileVersion>
      <AssemblyVersion>$([System.Version]::Parse($(PSCoreFileVersion)).Major).$([System.Version]::Parse($(PSCoreFileVersion)).Minor).0.$([System.Version]::Parse($(PSCoreFileVersion)).Revision)</AssemblyVersion>
    </PropertyGroup>

    <PropertyGroup>
      <RegexGitVersion>^v(.+)-(\d+)-g(.+)</RegexGitVersion>
      <PSCoreFileVersion Condition = "'$(PSCoreFileVersion)' == ''">$([System.Text.RegularExpressions.Regex]::Match($(PowerShellVersion), $(RegexGitVersion)).Groups[1].Value)</PSCoreFileVersion>
      <PSCoreBuildVersion Condition = "'$(PSCoreBuildVersion)' == ''">$([System.Text.RegularExpressions.Regex]::Match($(PowerShellVersion), $(RegexGitVersion)).Groups[1].Value)</PSCoreBuildVersion>
      <PSCoreAdditionalCommits>$([System.Text.RegularExpressions.Regex]::Match($(PowerShellVersion), $(RegexGitVersion)).Groups[2].Value)</PSCoreAdditionalCommits>
      <PSCoreCommitSHA>$([System.Text.RegularExpressions.Regex]::Match($(PowerShellVersion), $(RegexGitVersion)).Groups[3].Value)</PSCoreCommitSHA>

      
      <PSCoreFormattedVersion Condition = "'$(ReleaseTag)' != '' or '$(PSCoreAdditionalCommits)' == '0'">$(PSCoreBuildVersion) SHA: $(PSCoreCommitSHA)</PSCoreFormattedVersion>
      <PSCoreFormattedVersion Condition = "'$(PSCoreFormattedVersion)' == ''">$(PSCoreBuildVersion) Commits: $(PSCoreAdditionalCommits) SHA: $(PSCoreCommitSHA)</PSCoreFormattedVersion>

      

      
      <Version>$(PSCoreFileVersion)</Version>
      <InformationalVersion>$(PSCoreFormattedVersion)</InformationalVersion>
      <ProductVersion>$(PSCoreFormattedVersion)</ProductVersion>

      
      <PackageVersion>$(PSCoreBuildVersion)</PackageVersion>

      <ApplicationIcon Condition="$(ProductVersion.Contains('preview'))">..\..\assets\Powershell_av_colors.ico</ApplicationIcon>
      <ApplicationIcon Condition="$(ProductVersion.Contains('daily'))">..\..\assets\Powershell_avatar.ico</ApplicationIcon>
      <ApplicationIcon Condition="!$(ProductVersion.Contains('preview')) And !$(ProductVersion.Contains('daily'))">..\..\assets\Powershell_black.ico</ApplicationIcon>

    </PropertyGroup>

    
    <RemoveDir Directories="gen\SourceGenerated" Condition="Exists('gen\SourceGenerated')" />

    

  </Target>

  <PropertyGroup>
    <Product>PowerShell</Product>
    <Company>Microsoft Corporation</Company>
    <Copyright>(c) Microsoft Corporation.</Copyright>
    <AssemblyTitle>PowerShell 7</AssemblyTitle>

    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13.0</LangVersion>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <NeutralLanguage>en-US</NeutralLanguage>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
    <DisableImplicitNamespaceImports_DotNet>true</DisableImplicitNamespaceImports_DotNet>

    <DelaySign>true</DelaySign>
    <AssemblyOriginatorKeyFile>../signing/visualstudiopublic.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <HighEntropyVA>true</HighEntropyVA>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);CORECLR</DefineConstants>
    <IsWindows Condition="'$(IsWindows)' =='true' or ( '$(IsWindows)' == '' and '$(OS)' == 'Windows_NT')">true</IsWindows>
  </PropertyGroup>

  
  <PropertyGroup Condition=" '$(IsWindows)' != 'true' ">
    <DefineConstants>$(DefineConstants);UNIX</DefineConstants>
  </PropertyGroup>

  
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  
  <PropertyGroup Condition=" '$(AppDeployment)' == 'FxDependent' ">
    
    <AppHostDotNetSearch>EnvironmentVariable;Global</AppHostDotNetSearch>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(AppDeployment)' == 'FxDependentDeployment' ">
    
    <AppHostDotNetSearch>Global</AppHostDotNetSearch>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(AppDeployment)' == 'SelfContained' ">
    <AppHostDotNetSearch>AppLocal</AppHostDotNetSearch>
  </PropertyGroup>

  
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunEmitSymbols>true</PublishReadyToRunEmitSymbols>
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  
  <PropertyGroup Condition=" '$(Configuration)' == 'StaticAnalysis' ">
    <Optimize>true</Optimize>
    
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <Features>strict</Features>
  </PropertyGroup>

  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
