<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\Test.Common.props" />

  <PropertyGroup>
    
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>

    
    <GenerateDependencyFile>false</GenerateDependencyFile>

    
    <PublishDir>..\..\Modules\IsolatedModule</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="All" />
  </ItemGroup>

</Project>
