<?xml version="1.0" encoding="utf-8"?>
<schema targetNamespace="http://schemas.microsoft.com/maml/2004/10"
    xmlns:doc="http://schemas.microsoft.com/maml/internal"
    xmlns:maml="http://schemas.microsoft.com/maml/2004/10"
    xmlns="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    blockDefault="#all"
    xml:lang="en">
  
  <annotation>
    <documentation>This schema describes MAML (Microsoft Assistance Markup Language). MAML is intended for software documentation. In particular, MAML is intended to accommodate the needs of Microsoft documentation.</documentation>
    <documentation>The schema is broken into three main areas: end user, developer and IT Pro. These areas represent the main categories of Microsoft documentation.</documentation>
    <documentation>The namespace uri for this version of MAML is: http://schemas.microsoft.com/maml/2004/10.</documentation>
    <documentation>Each backwards-incompatible revision to MAML will require that the date fields be appropriately incremented in uri of the updated version of the MAML schema.</documentation>
  </annotation>
  <include schemaLocation="base.xsd"/>
  <complexType name="programmingLanguageType">
    <simpleContent>
      <extension base="maml:devLanguagesType"/>
    </simpleContent>
  </complexType>
  <element name="programmingLanguage" type="maml:programmingLanguageType">
    <annotation>
      <documentation>Specifies a programming language.</documentation>
      <appinfo>
        <doc:localizable>false</doc:localizable>
      </appinfo>
    </annotation>
  </element>
  <simpleType name="operatingSystemEnumType">
    <restriction base="token">
      <enumeration value="Win95"/>
      
      <enumeration value="Win98"/>
      
      <enumeration value="Win98Se"/>
      
      <enumeration value="WinMe"/>
      
      <enumeration value="WinNt4Server"/>
      
      <enumeration value="WinNt4Workstation"/>
      
      <enumeration value="Win2kProfessional"/>
      
      <enumeration value="Win2kServer"/>
      
      <enumeration value="Win2kAdvanced"/>
      
      <enumeration value="Win2kDatacenter"/>
      
      <enumeration value="Win2kServerApplianceKit"/>
      
      <enumeration value="WinXpHome"/>
      
      <enumeration value="WinXpProfessional"/>
      
      <enumeration value="WinXpMediaCenter"/>
      
      <enumeration value="WinXpTablet"/>
      
      <enumeration value="WinXpEmbedded"/>
      
      <enumeration value="Win2003Server"/>
      
      <enumeration value="WinCeDotNet"/>
      
    </restriction>
  </simpleType>
  <simpleType name="operatingSystemFamiliesEnumType">
    <restriction base="token">
      <enumeration value="Win9xFamily"/>
      
      <enumeration value="WinNt4Family"/>
      
      <enumeration value="Win2kFamily"/>
      
      <enumeration value="WinXpFamily"/>
      
      <enumeration value="WinCeFamily"/>
      
    </restriction>
  </simpleType>
  <simpleType name="platformStringType">
    <union memberTypes="maml:operatingSystemEnumType maml:operatingSystemFamiliesEnumType">
      <simpleType>
        <restriction base="token">
          <enumeration value="EcmaCli"/>
          
        </restriction>
      </simpleType>
    </union>
  </simpleType>
  <complexType name="platformType">
    <simpleContent>
      <extension base="maml:platformStringType"/>
    </simpleContent>
  </complexType>
  <element name="platform" type="maml:platformType">
    <annotation>
      <documentation>Specifies the identifier for a platform (such as an operating system version).</documentation>
      <appinfo>
        <doc:localizable>false</doc:localizable>
      </appinfo>
    </annotation>
  </element>
  <complexType name="platformsType">
    <sequence>
      <element ref="maml:platform" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  <element name="platforms" type="maml:platformsType">
    <annotation>
      <documentation>Describes a collection of platform elements.</documentation>
      <appinfo>
        <doc:localizable>n/a</doc:localizable>
      </appinfo>
    </annotation>
  </element>
</schema>
