<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <Import Project="..\..\PowerShell.Common.props" />
  <PropertyGroup>
    <Description>PowerShell SDK metapackage</Description>
    <PackageId>Microsoft.PowerShell.SDK</PackageId>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.PowerShell.Commands.Management\Microsoft.PowerShell.Commands.Management.csproj" />
    <ProjectReference Include="..\Microsoft.PowerShell.Commands.Utility\Microsoft.PowerShell.Commands.Utility.csproj" />
    <ProjectReference Include="..\Microsoft.PowerShell.ConsoleHost\Microsoft.PowerShell.ConsoleHost.csproj" />
    <ProjectReference Include="..\System.Management.Automation\System.Management.Automation.csproj" />
  </ItemGroup>
</Project>
